# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_predict_right', models.NullBooleanField()),
                ('predict_num', models.IntegerField(null=True)),
            ],
        ),
    ]
