# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderPredict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderpredictions',
            name='predict_num',
            field=models.IntegerField(),
        ),
    ]
