# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderPredict', '0004_auto_20170319_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderpredictions',
            name='is_predict_right',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='genderpredictions',
            name='predict_num',
            field=models.IntegerField(default=0),
        ),
    ]
