# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderPredict', '0007_auto_20170319_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderpredictions',
            name='predict_num',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
