# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderPredict', '0009_auto_20170319_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderpredictions',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
